version: '3.7'
services:
  mongoDevelopment:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: development
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - 27017:27017
    volumes:
      - ./dbDevelopment:/data/db

  mongoTest:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - 27018:27017
    volumes:
      - ./dbTest:/data/db

volumes:
  dbDevelopment:
  dbTest: